name: flutter_oct
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/perfil.jpg
    - assets/mach.png
    - assets/tarjeta1.png
    - assets/tarjeta2.png
    - assets/machLogo.png
  
  fonts: 
   - family: Gotham
     fonts:
     - asset: fonts/Gotham-Ultra.otf
     - asset: fonts/Gotham-Light.otf
     - asset: fonts/Gotham-Medium.otf
     - asset: fonts/Gotham-Bold.otf

splashscreen: ^1.3.0
